# Site settings
title: Brenton Forrest
description: 'Business Card Page'
url: 'https://github.com/Brenton-Forrest/Brenton_Forrest'
baseurl: ''
profilepic: '/images/tzuehlke.jpg'
bkimage: '/images/nature-forest-trees-fog-4827.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Brenton Forrest'
  email: s3863020@student.rmit.edu.au
  twitter_username:
#  facebook_username: joshgerdes
  github_username:  Brenton-Forrest
  linkedin_username:
  meetup_name:

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']

theme: jekyll-theme-time-machine